# Generated by Django 4.2.7 on 2026-06-02 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(max_length=100)),
                ('mentor_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Dijadwalkan'), ('ongoing', 'Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='scheduled', max_length=20)),
                ('duration', models.IntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='bookings.booking')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
