# Generated by Django 6.0.6 on 2026-06-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentorprofile",
            options={
                "verbose_name": "Mentor Profile",
                "verbose_name_plural": "Mentor Profiles",
            },
        ),
    ]
