# Generated by Django 4.2.7 on 2026-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
