# Generated by Django 4.2.7 on 2026-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Menunggu Pembayaran'), ('pending', 'Menunggu'), ('accepted', 'Diterima'), ('rejected', 'Ditolak'), ('ongoing', 'Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20),
        ),
    ]
