# Generated by Django 4.2.7 on 2026-06-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_invoice_amount_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Menunggu Pembayaran'), ('pending', 'Menunggu'), ('accepted', 'Diterima'), ('rejected', 'Ditolak'), ('ongoing', 'Berlangsung'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan'), ('paid', 'Lunas')], default='pending', max_length=20),
        ),
    ]
