# Generated by Django 6.0.6 on 2026-06-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_booking_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
    ]
